spring:
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: microservices
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver:http://localhost:8085


server:
  port: 8083


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    server-url:
#      defaultZone: http://localhost:8761/eureka
